services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Cad@str0Pesso@
      MYSQL_DATABASE: cadastro_pessoas
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: ./frontend  # Caminho para o Dockerfile do front-end
    ports:
      - "8080:8080"  # Mapeia a porta do contêiner para a porta 8080
    volumes:
      - ./frontend:/app  # Montar o diretório do projeto
    depends_on:
      - backend  # Certifique-se de que o backend está rodando antes do front-end

volumes:
  db_data:
