services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: Cad@str0Pesso@
      MYSQL_DATABASE: cadastro_pessoas
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Para persistir os dados do banco de dados

volumes:
  db_data: